# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: GeekWolf
email: twan@geekwolf.cloud
description: >- # this means to ignore newlines until "baseurl:"
  This site is for anyone using Microsoft cloud and wants some cool hidden gems,
  deep dives into features, architectures, cool scripts and utilities
url: "https://geekwolf.cloud" # the base hostname & protocol for your site, e.g. http://example.com

github_username:  geekwolf-cloud
excerpt_separator: <!--more-->
pagination:
  enabled: true
  per_page: 10
issues_repo: geekwolf-cloud/geekwolf.comments

#facebook_url: 
#twitter_url: 
rss_url: "https://geekwolf.cloud/feed.xml"
linkedin_url: "https://www.linkedin.com/in/twanvanbeers/"
#pinterest_url:
#instagram_url:

# Build settings
remote_theme: pages-themes/architect@v0.2.0
plugins: 
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-paginate-v2
  - jekyll-sitemap

permalink: /:year/:month/:day/:title:output_ext

# Build settings
markdown: kramdown
kramdown:
  input: GFM # GitHub Flavored Markdown
highlighter: rouge

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

