name: Get GeekWolf Subscribers

permissions:
  contents: write

on:
  schedule:
    - cron: '0 0 * * *' # Runs daily at midnight
  workflow_dispatch:

jobs:
  get-geekwolf-subscribers:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install sib-api-v3-sdk js-yaml

      - name: Get Sendinblue Subscribers
        env:
          SENDINBLUE_API_KEY: ${{ secrets.SENDINBLUE_API_KEY }}
        run: |
          node -e "
          const fs = require('fs');
          const yaml = require('js-yaml');
          const SibApiV3Sdk = require('sib-api-v3-sdk');
          const defaultClient = SibApiV3Sdk.ApiClient.instance;
          const apiKey = defaultClient.authentications['api-key'];
          apiKey.apiKey = process.env.SENDINBLUE_API_KEY;
          const apiInstance = new SibApiV3Sdk.ContactsApi();
          apiInstance.getLists().then(data => {
            console.log(data.lists);
            const list = data.lists.find(list => list.name === 'GeekWolf');
            console.log(list);
            if (list) {
              const subscriberCount = list.uniqueSubscribers;
              console.log('Number of subscribers:', subscriberCount);
              const yamlData = yaml.dump({ subscribers: subscriberCount });
              fs.writeFileSync('docs/_data/subscribers.yml', yamlData);
            } else {
              console.error('List named GeekWolf not found');
            }
          }).catch(error => {
            console.error(error);
          });
          "

      - name: Check for changes
        id: check_changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add docs/_data/subscribers.yml
          if git diff --quiet; then
            echo "no changes" && echo "changed=false" >> $GITHUB_ENV
          else
            echo "changes detected" && echo "changed=true" >> $GITHUB_ENV
          fi

      - name: Commit changes
        if: env.changed == 'true'
        run: |
          git commit -m 'Update subscriber count'
          git push origin main

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
